// apps/100ms-web-solid/src/components/Conference.jsx
// @ts-check
import { selectPeers, useHMSStore } from '@100mslive/solid-sdk';
import Peer from './Peer';
import DeviceSettings from './DeviceSettings';
import { For } from 'solid-js';

function Conference() {
  const peers = useHMSStore(selectPeers);

  return (
    <div className="conference-section">
      <h2>Conference</h2>
      <DeviceSettings />
      <div className="peers-container">
        <For each={peers()}>{peer => <Peer key={peer.id} peer={peer} />}</For>
      </div>
    </div>
  );
}

export default Conference;

// examples/prebuilt-react-integration/src/Conference.jsx
import { selectPeers, useHMSStore } from "@100mslive/react-sdk";
import Peer from "./Peer";

const Conference = () => {
  const peers = useHMSStore(selectPeers);
  return (
    <div className="conference-section">
      <h2>Conference</h2>
      <div className="peers-container">
        {peers.map((peer) => (
          <Peer key={peer.id} peer={peer}></Peer>
        ))}
      </div>
    </div>
  );
};
export default Conference;
